### PR TITLE
Update Contribution_Guidelines.md

### PR DESCRIPTION
**Pull request by Abkt2001**
Some mistakes

### CODE REVIEW

**Comment by rohank2502** [comment]
> 
> 
> Some mistakes

Did you create issue for this ?

**Comment by rohank2502** [comment]
> 
> 
> Some mistakes

1 issue 1 PR ? Did you read this ?

**Comment by Abkt2001** [comment]
Yes, I read. Sorry, but this is my first time solving the issues.

**Comment by rohank2502** [comment]
> 
> 
> Yes, I read. Sorry, but this is my first time solving the issues.

Ok Create new Issue and link both PR to respective issues

**Pull request merged**
